# Generated by Django 6.0.4 on 2026-04-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('tu_van', 'Tư vấn sản phẩm'), ('don_hang', 'Hỗ trợ đơn hàng'), ('hop_tac', 'Hợp tác / đối tác'), ('khieu_nai', 'Khiếu nại / góp ý'), ('khac', 'Khác')], default='tu_van', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liên hệ',
                'verbose_name_plural': 'Liên hệ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('website', 'Giao diện website'), ('san_pham', 'Chất lượng sản phẩm'), ('giao_hang', 'Tốc độ giao hàng'), ('ho_tro', 'Dịch vụ hỗ trợ'), ('tong_the', 'Trải nghiệm tổng thể')], default='tong_the', max_length=20)),
                ('satisfaction', models.CharField(choices=[('5', 'Rất hài lòng'), ('4', 'Hài lòng'), ('3', 'Bình thường'), ('2', 'Chưa hài lòng'), ('1', 'Rất không hài lòng')], default='5', max_length=1)),
                ('message', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phản hồi',
                'verbose_name_plural': 'Phản hồi',
                'ordering': ['-created_at'],
            },
        ),
    ]
