# Generated by Django 6.0.4 on 2026-04-22 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thanh toán thành công'), ('failed', 'Thanh toán thất bại')], default='pending', max_length=20)),
                ('order_info', models.CharField(blank=True, max_length=255)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('transaction_no', models.CharField(blank=True, max_length=50)),
                ('bank_code', models.CharField(blank=True, max_length=50)),
                ('bank_tran_no', models.CharField(blank=True, max_length=100)),
                ('pay_date', models.CharField(blank=True, max_length=30)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
